@extends('Backend.dashboard')
@section('title') @endsection
@section('content')
<div class="container-fluid"><h1 class="h3 text-gray-800 mb-4">Position, Township & District</h1>@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(session('danger'))<div class="alert alert-danger">{{ session('danger') }}</div>@endif<div class="row">
@php $cards=[['key'=>'district','title'=>'Districts','items'=>$districts,'columns'=>['Name']],['key'=>'township','title'=>'Townships','items'=>$townships,'columns'=>['Name','District']],['key'=>'position','title'=>'Positions','items'=>$positions,'columns'=>['Name']]]; @endphp
@foreach($cards as $card)<div class="col-lg-4 mb-4"><div class="card shadow"><div class="card-header d-flex justify-content-between align-items-center"><strong>{{ $card['title'] }} ({{ $card['items']->total() }})</strong><button class="btn btn-primary btn-sm open-lookup" data-type="{{ $card['key'] }}" title="Add"><i class="fas fa-plus"></i></button></div><div class="table-responsive"><table class="table table-bordered mb-0"><thead><tr>@foreach($card['columns'] as $column)<th>{{ $column }}</th>@endforeach<th class="text-center" style="width:90px">Actions</th></tr></thead><tbody>@forelse($card['items'] as $item)<tr><td>{{ $item->name }}</td>@if($card['key']==='township')<td>{{ optional($item->district)->name }}</td>@endif<td class="text-center text-nowrap"><button class="btn btn-outline-primary btn-sm edit-lookup" data-type="{{ $card['key'] }}" data-id="{{ $item->id }}" data-name="{{ $item->name }}" data-name-en="{{ $item->name_en }}" @if($card['key']==='township') data-district="{{ $item->district_id }}" @endif title="Edit"><i class="fas fa-edit"></i></button> <form class="d-inline" method="POST" action="{{ route('lookup.delete',['type'=>$card['key'],'id'=>$item->id]) }}">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm" onclick="return confirm('Delete this item?')" title="Delete"><i class="fas fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="{{ count($card['columns'])+1 }}" class="text-center">No data found.</td></tr>@endforelse</tbody></table></div><div class="card-footer py-2">{{ $card['items']->links('pagination::bootstrap-4') }}</div></div></div>@endforeach
</div></div>
<div class="modal fade" id="lookupManageModal" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="lookupManageTitle">Add</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><form id="lookupManageForm" method="POST">@csrf<div class="modal-body"><input type="text" name="name" id="manageName" class="form-control mb-2" placeholder="Name" required><input type="text" name="name_en" id="manageNameEn" class="form-control mb-2" placeholder="English name"><select name="district_id" id="manageDistrict" class="form-control"><option value="">Select District</option>@foreach($districtOptions as $district)<option value="{{ $district->id }}">{{ $district->name }}</option>@endforeach</select></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button><button class="btn btn-primary">Save</button></div></form></div></div></div>
@endsection
@section('ckeditor')<script>$(function(){var base='{{ url('/admin/news/lookup') }}',updateBase='{{ url('/admin/lookups') }}';function setup(type,id,name,nameEn,district){$('#lookupManageForm').attr('action',id?updateBase+'/'+type+'/'+id:base+'/'+type);$('#lookupManageForm').data('is-create',!id);$('#lookupManageTitle').text((id?'Edit ':'Add New ')+type.charAt(0).toUpperCase()+type.slice(1));$('#manageName').val(name||'');$('#manageNameEn').val(nameEn||'');$('#manageDistrict').val(district||'');$('#manageNameEn').toggle(type!=='district');$('#manageDistrict').toggle(type==='township');$('#lookupManageModal').modal('show')}$('.open-lookup').on('click',function(){setup($(this).data('type'))});$('.edit-lookup').on('click',function(){var b=$(this);setup(b.data('type'),b.data('id'),b.data('name'),b.data('name-en'),b.data('district'))});$('#lookupManageForm').on('submit',function(e){if(!$(this).data('is-create'))return;e.preventDefault();var form=$(this),data=form.serialize();$.post(form.attr('action'),data).done(function(){location.reload()}).fail(function(xhr){alert(xhr.responseJSON&&xhr.responseJSON.message?xhr.responseJSON.message:'Unable to save.')})})});</script>@endsection
